### PR TITLE
fix: missing parenthese when decompile cast operation

### PR DESCRIPTION
**Pull request by khanhnt2**
Fix issue #1

I'm not familiar with Move language. I saw this repo on my social feeds, it's great to see Vietnamese people make the project 😄

My fix is always to add parentheses to cast operation, even though it's a stand-alone expression. Not sure this is a good solution

### CODE REVIEW

**Comment by khanhnt2** [comment]
Maybe I have to implement 'Ret' operation for the better solution

**Comment by vhqtvn** [comment]
We already added brackets for casting operator but need to revert at some point due to syntax error. I'll check it again.

**Comment by aquynh** [comment]
@khanhnt2, thank you for the first ever pull req!

can you put the new testcases into a new separate file, rather than adding them to BasicCoin-test.move?

**Comment by khanhnt2** [comment]
@aquynh, I moved the tests to the new `CastOperation-test.move` file

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
